### ISSUE TITLE
spindle of serendipity is not under a free/libre license

### ISSUE THREAD

**Issue by ghost** [Calinou/awesome-godot#153]
The source code of spindle of serendipity is not under an open source license and thus violates the contributing guidelines.

**Comment by zacryol** [comment]
What? Yes it is, right here: https://gitlab.com/zacryol/spindle-of-serendipity/-/blob/master/LICENSE

**Comment by Calinou** [comment]
> What? Yes it is, right here: https://gitlab.com/zacryol/spindle-of-serendipity/-/blob/master/LICENSE

Apologies, I didn't see a link to the source code repository on the itch.io page. Could you edit the itch.io description to add a link to the source repository? (Since your GitLab profile is private, I couldn't find the source repository based on the samples repository's URL.)

Thanks in advance :slightly_smiling_face:

**Comment by zacryol** [comment]
There's a Source Code link under the "More Information" drop down menu.
I also un-privated my Gitlab profile

**Comment by ghost** [comment]
I also apologize. I didn't see it on the Itch.io page.

**Comment by Calinou** [comment]
I readded spindle of serendipity: https://github.com/godotengine/awesome-godot/commit/ec267f1edf6441f552e7625357d7fd8a4a222576
