### ISSUE TITLE
Policy about tutorials

### ISSUE THREAD

**Issue by TeddyDD** [Calinou/awesome-godot#19]
Do we adding links to best tutorials / tuorial videos like this: 
https://www.youtube.com/playlist?list=PLS9MbmO_ssyAXRl-_ktrebQBFxjSQt7UX

**Comment by Calinou** [comment]
Yes, I might add tutorials later.

**Comment by TeddyDD** [comment]
this is another tutorial worth adding: https://github.com/gokudomatic/godot/blob/master/demos/3d/kinematic_fps/documentation/Documentation.pdf https://github.com/gokudomatic/godot/tree/master/demos/3d/kinematic_fps

**Comment by akien-mga** [comment]
+1

**Comment by rolfpancake** [comment]
Tutorials are very important for newcomers. Because there is no maintained list on the website or in the docs it would be great to at least have one here.

Another Video Tutorial series:
[Andreas Esau - Godot Engine - Tutorial Series](https://www.youtube.com/playlist?list=PLPI26-KXCXpBtZGRJizz0cvU88nXB-G14)
