### ISSUE TITLE
Stuff in 3.2 category

### ISSUE THREAD

**Issue by TwinklePillar** [Calinou/awesome-godot#201]
Technically, stuff in the 3.2 category work in 3.3, however (like the Mitigate-IK script) there is stuff that is obsoleted by 3.3

**Comment by Calinou** [comment]
I made a change last week to clarify this: https://github.com/godotengine/awesome-godot/commit/8089846187c8efdfd12b514e422f623d6f9eb7ab

Can you make a list of all projects that are obsolete as of 3.3? I'd probably remove those from the list since people seem to be upgrading to 3.3 more quickly compared to previous versions.

**Comment by TwinklePillar** [comment]
Seeing as the obsoleted scripts would be obsoleted more likely by bugs, and I couldn't see any that are obsoleted by features, I can only see my Mitigate-IK script. Maybe add something like "OBSOLETED in 3.x.x" in their description for people who for some reason still use 3.2

**Comment by Calinou** [comment]
I removed Mitigate-IK from the list in https://github.com/godotengine/awesome-godot/commit/c51108738084218f6ed2d174e252aa3d55d9d7b0. ([3.2 is now considered EOL](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline))
